export const USER_COUNTRY_GET_REQUEST = 'USER_COUNTRY_GET_REQUEST'
export const USER_COUNTRY_GET_SUCCESS = 'USER_COUNTRY_GET_SUCCESS'
export const USER_COUNTRY_GET_FAILURE = 'USER_COUNTRY_GET_FAILURE'

export const getUserCountry = () => ({ type: USER_COUNTRY_GET_REQUEST })
